#import "@preview/thesist:1.0.2": flex-caption, subfigure-grid

= Experimental Measurements


By this point, a plasma was already defined, but there's still a question in the air. How can one make it?

In this chapter not only this question is answered, but it's also described exactly what parameters are measured and taken into account to support all the work of modelling presented in @modelling-nh3-plasmas, and ultimately, to run simulations.


== Experimental Setup and Diagnostics

Plasmas can be generated using two popular sources: Direct Current (DC) discharge and Radio Frequency (RF) discharge. 



The *DC glow discharge* system consists usually of a cylindrical discharge tube excited by two planar electrodes positioned in a side-arm configuration, as in @dc. 

#figure(
  image("../Images/glow_discharge.jpg", width: 70%),
  caption: [Simple schematic of a DC glow discharge system, adapted from @alireza]
)<dc>


This classical geometry provides a positive column region and a central, quasi-neutral plasma volume characterized by axial uniformity and relatively low electric field. The discharge is generated within a cylindrical Pyrex tube; Pyrex is selected for its excellent vacuum properties, optical transparency for diagnostic access, and well-documented surface characteristics. Two cylindrical stainless steel electrodes are positioned in perpendicular side-arms, placing them outside the direct line-of-sight for axial optical diagnostics. Gas is introduced at one end of the main tube and exhausted at the other, establishing a well-defined flow direction and residence time.

The discharge is sustained by a high-voltage DC power supply capable of delivering up to several kilovolts and tens of milliamperes. A critical component in the electrical circuit is a high-power, non-inductive ballast resistor (e.g., 150 kΩ) connected in series between the power supply and the anode. This resistor is necessary because glow discharges can exhibit negative differential resistance under certain operating conditions, where the voltage across the discharge decreases as current increases. This creates an electrically unstable situation that can lead to a runaway current increase, potentially causing the discharge to transition into an uncontrolled _arc_: a high-current, high-temperature discharge that could damage the electrodes and equipment. The ballast resistor provides positive resistance that limits current flow and stabilizes the discharge at a controlled operating point.

A key advantage of this DC setup is the ability to directly measure the fundamental plasma parameter that governs electron kinetics: the axial electric field, $E$. This is accomplished via two tungsten wire probes embedded in the reactor wall and separated by a known axial distance, $L$@MorilloCandas2019. By measuring the floating potential difference, $Delta V$, between these probes, the axial electric field in the positive column is determined as:

$ E = (Delta V) / L $

The gas number density, $N$, is calculated using the ideal gas law:

$ N = p / (k_B T_"gas") $

where the pressure $p$ is measured by a capacitance manometer and the gas temperature $T_"gas"$ is determined spectroscopically. The reduced electric field, $E\/N$, is thus obtained directly from experimental measurements. This parameter is of paramount importance as it uniquely determines the shape of the EEDF and, consequently, the rate coefficients for all electron-impact reactions.



The plasma generated by a *RF discharge* consists of a parallel-plate configuration housed within a larger cylindrical Pyrex vacuum chamber, where the plasma is confined. A radio frequency generator powers the reactor through a _match box_ (see @matchBox), an intermediary device that matches the electrical impedance of the RF generator (typically 50 $Omega$) to the impedance of the plasma reactor. The plasma has a complex impedance ($Z_("plasma") = R_p + "j"X_p$@gross_roppel_2012) that doesn't match the standard 50 $Omega$ of the generator and cables, and it also changes continuously with plasma conditions. This matching prevents power loss from reflection and ensures efficient energy delivery to the plasma. The RF power is transmitted to the plasma by a three-electrode system consisting of three copper sheets rolled around the Pyrex tube. Two grounded electrodes are located at the extremes of the reactor, and one high-power electrode is placed in the middle, as seen in @rf. This configuration helps to control the plasma volume (confined between the two grounded electrodes) and ensures homogeneity of the discharge.

#subfigure-grid(
  figure(
    image("../Images/matchBox.jpg", width: 70%),
    caption: [Example of a Solayl customized Match box@solayl_custom_matchers]
  ), <matchBox>,


  figure(
    image("../Images/rf.png", width: 90%),
    caption: [Simple schematic of a RF discharge system@MorilloCandas2019]
  ), <rf>,

  kind: image,
  align: top,
  columns: (1fr, 1fr),
  rows: 5cm,
  caption: [RF discharge setup showing match box and electrode configuration]
)

In both the DC and RF experimental systems, the gas flow rates are precisely regulated using digital mass flow controllers, which allow for accurate control of the total gas flow and the $N_2:H_2$ mixing ratio. The vacuum systems are designed to achieve a base pressure in the high-vacuum regime ($<10^(-6)$ mbar) prior to each experiment. This is accomplished using a two-stage pumping system, typically consisting of a turbomolecular pump backed by a dry scroll or rotary vane pump@ben. Achieving a low base pressure is critical for evacuating contaminants and the gases themselves, ensuring a clean experimental environment. The operating pressure is monitored with a temperature-independent capacitance manometer, which provides pressure readings irrespective of gas composition.   

=== Plasma Diagnostics

A comprehensive understanding of the $N_2$-$H_2$ plasma chemistry necessitates a multi-faceted diagnostic approach. A suite of complementary techniques is employed to characterize the plasma's electrical properties, gas-phase composition, and internal energy distributions.

*Laser-Induced Fluorescence (LIF)* is a non-invasive optical technique used for in-situ detection of specific ground-state radical species. It is the key diagnostic for measuring the absolute densities of the highly reactive intermediates that govern the ammonia formation chemistry but are often present in concentrations too low to be detected by OES. The technique involves using a tunable laser to excite a specific *rovibronic transition* (simultaneous change in the #strong[ro]tational, #strong[vib]rational, and elect#strong[ronic] states)  of the target species. The subsequent fluorescence, emitted as the excited species radiatively relaxes, is collected at a 90° angle to the laser beam. The intensity of the fluorescence signal is directly proportional to the number density of the species in the probed ground state@van_2007. The NH radical is typically detected by exciting the $A^3 Pi arrow.l X^3 Sigma^-$ electronic transition@dai_2025@pastorek2022time@ubachs_1984, near 336 nm band, while the $N H_2$ radical is detected via its $tilde(A)^2 A_1 arrow.l tilde(X)^2 B_1$ electronic transition@gong_gong@brackmann_2017, near 385 nm.

*Photofragment Translational Spectroscopy (PFTS)* explores the dynamics of gas-phase molecular photodissociation by measuring the speeds and directions of resulting fragments. A UV laser breaks a molecule apart in a molecular beam, and by measuring how fast the fragments fly apart, one can determine the energy distribution and bond dissociation energies@michael_king_michael_thomas_2011. The technique follows energy conservation: 

$ E_"photon" = "BDE" + E_"int" + "TKER" $

where the photon energy is partitioned between bond breaking ($"BDE"$), internal fragment energy, and kinetic energy release ($"TKER"$)@michael_yuan_yang_2018. Advanced variants include H-atom Rydberg tagging (HRA-PTS) for high-resolution measurements of hydrogen-containing molecules@michael_yuan_yang_2018, and Velocity Map Imaging (VMI) for simultaneous 2D imaging of fragment velocity distributions@suits_2018. These methods provide detailed information about dissociation dynamics and serve as benchmarks for theoretical models@felder1994photofragment@king_oliver_nix_ashfold_2009.   

*Vacuum Ultraviolet (VUV) Absorption Spectroscopy* probes high-energy electronic transitions (wavelengths $< 200$ nm) in molecules and can provide unique "fingerprints" that distinguish structural isomers.
VUV photons access $sigma -> sigma^*$ and $n -> sigma^*$ transitions unavailable at longer wavelengths@hermann_zander_hannes. Since nearly all molecules contain $sigma$ bonds, VUV spectroscopy is near-universal, with the notable exception of inert gases like He, Ar, and $"H"_2$@du2005experimental@krishnan2023uv. The technique requires a vacuum optical path ($< 10^(-5)$ mbar) because atmospheric $"O"_2$ and water vapor strongly absorb VUV radiation. Specialized optics ($"MgF"_2$ or LiF windows) and detectors are necessary. 

*Electron Paramagnetic Resonance (EPR) Spectroscopy*, also known as Electron Spin Resonance (ESR), is uniquely sensitive to species with unpaired electrons: free radicals, transition metal complexes, and material defects. When an external magnetic field ($B_0$) is applied, electron spin states split (Zeeman effect), and microwave radiation at the resonant frequency induces transitions between these states@bendix_2017@wertz1972electron:

$ Delta E = h nu = g mu_B B_0 $

where the g-factor ($g approx 2.0023$ for free electrons) is sensitive to the electronic environment, serving as a "fingerprint" for paramagnetic species. Hyperfine coupling with nearby nuclei splits the signal into multiple lines, with $2N I + 1$ lines for $N$ equivalent nuclei of spin $I$, providing structural information about bonding and distances.

EPR spectrometers use microwave sources, resonant cavities, and swept magnetic fields to record spectra, typically displayed as first derivatives@wertz1972electron.

*Gas-Phase Chemiluminescence Titration* exploits light emission from rapid stoichiometric reactions for highly sensitive species quantification. Chemiluminescence produces signals against a dark background, achieving detection limits of parts-per-billion to parts-per-trillion—far superior to absorption spectroscopy@stedman1972analysis@prok1961effect.

#v(.5cm)

For this work, the following techniques were employed:

*Optical Emission Spectroscopy (OES)* was used to obtain the plasma temperature. OES analyzes the light emitted by electronically excited species. The emission is collected via an optical fiber, dispersed by a spectrometer, and recorded by a photomultiplier detector@MorilloCandas2019. The resulting spectrum contains characteristic emission lines and bands that serve as fingerprints for the excited species present in the discharge@jamroz2006optical@yadava2022vibrational. For $N_2$-$H_2$ plasmas, key features include the $N_2$ Second Positive System ($C^3 Pi_u -> B^3 Pi_g$), the $N_2^+$ First Negative System ($B^2 Sigma_u^+ -> X^2 Sigma_g^+$), the NH ($A^3 Pi -> X^3 Sigma^-$) transition around 336 nm, and atomic hydrogen lines from the Balmer series (e.g., $H_alpha$ at 656.3 nm)@li_zhang_chen_zhang_wang_xia_2014@wróbel_i. The rotational temperature ($T_"rot"$) is determined by analyzing the intensity distribution within the rotational structure of a molecular emission band. A common and reliable method involves fitting a simulated spectrum of the $N_2$ Second Positive System (e.g., the 0-0 band at 337.1 nm) to the experimentally measured spectrum, with $T_"rot"$ as the fitting parameter. For the low-pressure conditions investigated here, the rotational-translational relaxation is sufficiently fast to assume that the rotational temperature of the $N_2(C^3 Pi_u)$ state is in thermal equilibrium with the kinetic temperature of the background gas, i.e., $T_"rot" approx T_"gas"$@bruggeman2014gas@zhang_shi_xu_miao_ma_ren_zhang_yi_2015. 

*Fourier-Transform Infrared (FTIR) Spectroscopy* identifies molecules concentrations by probing quantized vibrational modes (stretching and bending). IR absorption occurs when photons match vibrational energy differences and cause dipole moment changes. Homonuclear diatomics like $"N"_2$ and $"O"_2$ are therefore IR-inactive; their vibration does not cause a change in dipole moment. 

FTIR uses a Michelson interferometer: a moving mirror creates an interferogram (time-domain signal containing all IR frequencies), which is Fourier-transformed to produce the frequency-domain spectrum. This offers _Fellgett's Advantage_ (simultaneous measurement of all frequencies, faster acquisition) and _Jacquinot's Advantage_ (no restrictive slits, higher signal-to-noise). The resulting spectrum ($"cm"^(-1)$ vs. absorbance) provides unique molecular "fingerprints."

#subfigure-grid(
  figure(
    image("../Images/ftir.png", width: 70%),
    caption: [Schematic of a FTIR spectrometer@delrue_2023]
  ), <ftir>,


  figure(
    image("../Images/bruker.png", width: 100%),
    caption: [Bruker Vertex 70 FTIR spectrometer, used in this work@vandenbrouckeafbraak]
  ), <bruker>,

  kind: image,
  align: top,
  columns: (1fr, 1fr),
  rows: 7cm,
  caption: [FTIR spectrometer setup]
)

For $"NH"_3$ detection, the key vibrational modes include the N-H symmetric stretching (~3300 $"cm"^(-1)$), the N-H bending (~1600 $"cm"^(-1)$), and the umbrella mode (~950-1200 $"cm"^(-1)$)@hargreaves_li_bernath_2011. In this work, ammonia concentration was quantified by fitting the FTIR absorption spectra in the two latter specific regions. The reasons are discussed later in this chapter.

The temperature of the plasma tube wall ($"T"_"wall"$) was monitored using a *fiber optic temperature sensor*. This system consisted of an optical fiber probe with a thermosensitive crystal at its tip (doped magnesium phosphate [confirm!]), which enabled non-intrusive temperature measurements without electromagnetic interference from the plasma environment. Light transmitted through the optical fiber excited the crystal, which emitted a temperature-dependent fluorescent response that was transmitted back through the fiber to a monitoring unit. This setup allowed for continuous real-time temperature monitoring throughout the plasma treatment process, ensuring precise control of the thermal conditions during ammonia activation.


== Experimental Campaign at LPP Laboratory

A research stay was conducted at the LPP with two main objectives. First, to reproduce the measurements previously performed at LPP that had been used as input data for the group's plasma simulations, using the same experimental conditions and a similar setup. This replication aimed to validate the consistency of the measurements and ensure reliable comparison with the simulation results.
Second, a novel "building-up" experiment was performed for the first time, following the methodology proposed by Morillo-Candas in their PhD thesis@MorilloCandas2019. This experiment involved plasma treatment of $"N"_2$-$"H"_2$ mixtures in static conditions to study the temporal evolution of $"NH"_3$ concentration. The reactor cleaning protocol utilized sequential $"O"_2$ plasma and $"CO"_2$ flushing to ensure a contamination-free environment before the ammonia formation measurements. 

=== RF "Building-Up" Experiment

The "building-up" experiment, conducted using the Radio Frequency (RF) discharge reactor, was a dedicated methodology designed to study the **time evolution of ammonia ($"NH"_3$) concentration** in $"N"_2$-$"H"_2$ plasmas. This section details the methodology, experimental setup, and procedures associated with this technique.

The building-up technique works in **static conditions (closed reactor, without gas flow)** to remove the influence of gas residence time ($tau_"res"$) and measure the **cumulative effect of multiple plasma pulses** on ammonia formation, monitoring the gas mixture evolution through FTIR spectroscopy until steady-state concentration was reached. 

The plasma was generated in a short, cylindrical Pyrex tube (2 cm inner diameter, 23 cm length). The RF discharge was powered at 13.6 kHz using a three-electrode system (two grounded, one high-power electrode, see @rf) controlled by the Vigilant RF Lab impedance matching system (see @matchBox) and the total RF power imposed was 40 W.

*Gas Flow Control:* Gas flow rates were controlled using Bronkhorst F-201 mass flow controllers, factory-calibrated for nitrogen ($"N"_2$). The total gas flow rate was set to 50 sccm for $"N"_2$-$"H"_2$ mixtures. Since mass flow controllers measure flow based on the thermal properties of gases, correction factors were required when using gases other than the calibration gas. Each gas species has a characteristic thermal conductivity constant, and the conversion factor between gases is determined by the ratio of these constants: the thermal constant of the actual gas divided by the thermal constant of the calibration gas ($"N"_2$). To achieve a desired flow rate for a given gas, the setpoint on the controller was adjusted by multiplying the target flow rate by the appropriate gas-specific conversion factor obtained from the manufacturer's gas conversion tables. The mass controllers were interconnected, requiring only one connection to the computer for control via FlowDDE communication protocol and FlowView software interface.

*FTIR Spectroscopy:* The gas composition was monitored using a Bruker Vertex 70 FTIR spectrometer operated with OPUS software in Rapid Scan mode. The FTIR detector required periodic refilling (every 4 hours) with liquid nitrogen to maintain low temperature and reduce contamination from ambient infrared radiation. Background spectra were recorded before each experimental run to ensure accurate measurements.

*Safety Considerations:* For safety reasons, the tube transporting hydrogen from the gas bottle to the first mass controller was constructed of metal. Prior to each experimental campaign, a cleaning procedure was performed by flowing gases through the system to evacuate residual gases and contaminants from previous experiments.

==== Detailed Experimental Protocol

The building-up experiment followed a rigorous step-by-step protocol to ensure reproducibility and eliminate contamination:

*Pre-treatment Phase (Reactor Cleaning):*
1. All valves were opened to establish gas flow
2. The RF pulser and impedance matching system were activated
3. Pure $"O"_2$ flow was set to maximum
4. The $"O"_2$ plasma was maintained for 15 minutes to clean the reactor walls and remove surface contaminants (oxygen plasma is particularly effective as a cleaning agent)
5. The pulser and impedance matching system were then deactivated
6. A background spectrum was measured with the FTIR

*Secondary Cleaning Phase (Oxygen Removal):*
7. The $"O"_2$ mass flow controller was set to zero and the system was evacuated to low pressure
8. The $"CO"_2$ mass flow controller was set to maximum with all valves open
9. $"CO"_2$ gas flow was maintained for 10 minutes to thoroughly flush the system and remove any residual oxygen from the previous cleaning step
10. The $"CO"_2$ mass flow controller was set to zero and the system was evacuated to low pressure

*Reactive Gas Preparation Phase ($"N"_2$-$"H"_2$ Mixture):*
11. The desired gas flow rates were established for $"N"_2$ and $"H"_2$ (50 sccm total) using the mass flow controllers
12. The pump valve was closed, allowing pressure to build up inside the reactor
13. When the operating pressure (typically 5 Torr) was reached, it was recorded. If pressure exceeded 5 Torr, the pump valve could be slightly opened to release excess gas
14. The valve-switch before the FTIR sample compartment was closed to isolate the static gas volume inside the reactor
15. Gas flows were set to zero and feed valves (yellow valves) were closed, establishing the static conditions for the building-up experiment

*Measurement Phase (Ammonia Formation Tracking):*
16. The impedance matching was optimized using Vigilant RF Lab software (successful matching was confirmed by visual observation of plasma formation and characteristic plasma color)
17. FTIR Rapid Scan measurements were initiated using a programmed loop in the OPUS Method Editor
18. Feed valves (yellow valves) were opened to allow optical access through the reactor
19. The plasma pulsing sequence was executed: 500 trains $times$ 10 pulses $times$ 5-10 ms On-Off, resulting in a total accumulated plasma ON time ($T_"ON"$) of 25 s
20. Spectra were recorded in the post-discharge period after each train of pulses, allowing measurement of $"NH"_3$ concentration evolution

*Post-Measurement Phase:*
21. The operating pressure was recorded for data analysis
22. All valves were opened to evacuate the system to low pressure
23. The system was prepared for the next measurement cycle

*Data Treatment:* The ammonia concentration was quantified from FTIR spectra by fitting the characteristic vibrational bands in the [1050, 1800] $"cm"^(-1)$ range. Since the spectral measurements were taken in the post-discharge after each train of pulses, and the characteristic time for vibrational relaxation is short compared to the measurement time scale, the spectra were fitted assuming thermal equilibrium.

==== Results and Kinetic Analysis

The measurement of ammonia concentration ([$"NH"_3$]) as a function of the total plasma ON time ($T_"ON"$) revealed the temporal evolution of ammonia formation under static conditions. The building-up technique allowed for the observation of how $"NH"_3$ accumulates in the reactor over successive plasma pulses, providing insights into the formation kinetics and potential saturation mechanisms.

The analysis focused on:

- *Initial formation rate:* The rate at which $"NH"_3$ is produced during the early stages of the experiment, which reflects the efficiency of nitrogen-hydrogen recombination processes
- *Pressure dependence:* How the operating pressure (typically 5 Torr) affects the formation rate and final concentration
- *Power dependence:* The relationship between RF power (40-80 W) and ammonia production efficiency
- *Temporal evolution:* The complete time-dependent behavior of [$"NH"_3$] from initial formation to potential steady-state

This experimental approach provided valuable data for validating the kinetic model predictions regarding ammonia formation pathways and rates under pulsed plasma conditions. The static reactor configuration eliminated complications from gas flow and residence time effects, allowing for direct observation of the intrinsic chemical kinetics of the $"N"_2$-$"H"_2$ plasma system.

The methodology included:
- Systematic parameter variation
- Multiple measurements for statistical significance
- Cross-validation between different diagnostics
- Detailed documentation of experimental procedures

=== Measurement protocols and procedures
Standardized measurement protocols were developed to ensure reproducibility:

*Gas handling procedures*: Purification, mixing, flow control
*Discharge startup*: Gradual voltage increase, stabilization time
*Diagnostic timing*: Synchronization of different measurements
*Data acquisition*: Automated data collection and storage

The protocols included:
- Pre-measurement calibration procedures
- During-measurement monitoring
- Post-measurement data validation
- Quality control checks

=== Data acquisition and processing
Data acquisition and processing were automated to ensure consistency:

*Real-time monitoring*: Continuous monitoring of key parameters
*Automated data collection*: Computer-controlled data acquisition
*Data validation*: Real-time checks for data quality
*Post-processing*: Automated data analysis and plotting

The data processing included:
- Signal filtering and noise reduction
- Calibration and background subtraction
- Uncertainty estimation
- Format standardization for model comparison

=== Reproducibility assessment
Reproducibility was assessed through:

*Repeated measurements*: Multiple measurements under identical conditions
*Operator variation*: Measurements by different operators
*Time stability*: Measurements over extended time periods
*Cross-validation*: Comparison between different diagnostic techniques

The reproducibility assessment included:
- Statistical analysis of repeated measurements
- Uncertainty estimation from reproducibility data
- Identification of systematic errors
- Development of improved procedures

== Results and Analysis

=== Gas and Wall Temperatures

The gas and wall temperatures were systematically measured across different operating conditions:

*Temperature measurements*: Gas temperature was measured using spectroscopic techniques, while wall temperature was monitored using thermocouples and infrared cameras.

*Parameter dependencies*: Temperature showed strong dependencies on:
- Discharge power density
- Gas pressure and composition
- Flow rates and residence time
- Wall material and cooling

*Temperature profiles*: Both spatial and temporal temperature profiles were characterized to understand heat transfer mechanisms and optimize operating conditions.

=== $["NH"_3]$ vs Temperature Analysis

To illustrate the relationship between ammonia concentration and temperature, several representative data points were selected from the experimental campaign:

*Low temperature regime (300-400 K)*: 
- $["NH"_3]$ typically 0.1-0.5% of total gas composition
- Limited by slow reaction kinetics
- Strong dependence on residence time

*Medium temperature regime (400-600 K)*:
- $["NH"_3]$ increases to 1-3% of total gas composition
- Optimal conditions for ammonia synthesis
- Balance between production and decomposition

*High temperature regime (600-800 K)*:
- $["NH"_3]$ decreases due to thermal decomposition
- Competing reactions become dominant
- Energy efficiency considerations

The temperature dependence analysis revealed optimal operating conditions and provided insights into the underlying reaction mechanisms.

=== Discharge characteristics (E/N vs NR)
The discharge characteristics were analyzed in terms of:

*Current-voltage characteristics*: Relationship between discharge current and voltage
*Power dissipation*: Electrical power consumed by the discharge
*Discharge stability*: Temporal and spatial stability of the discharge
*Parameter dependencies*: Effect of pressure, gas composition, and gap distance

Key findings included:
- Discharge stability over wide parameter ranges
- Power efficiency optimization opportunities
- Parameter regions for optimal ammonia production
- Comparison with literature data

=== Species density profiles
Species density profiles were measured and compared with model predictions:

*Neutral species*: $"N"_2$, $"H"_2$, $"NH"_3$, N, H, NH, $"NH"_2$
*Excited species*: $"N"_2^*$, $"H"_2^*$, $"NH"^*$
*Ionic species*: $"N"_2^+$, $"H"_2^+$, $"NH"_3^+$

The analysis included:
- Spatial profiles across the discharge gap
- Temporal evolution of species concentrations
- Parameter dependencies (E/N, pressure, composition)
- Comparison with model predictions

=== Spectra from LPP Laboratory

During the experimental campaign at LPP, several spectroscopic measurements were performed to characterize the plasma:

*Optical emission spectra*: High-resolution spectra were recorded in the 200-800 nm range, revealing:
- $"N"_2$ molecular bands ($B^3 Pi_g -> A^3 Sigma_u^+$, $C^3 Pi_u -> B^3 Pi_g$)
- $"H"_2$ molecular bands (Fulcher-$alpha$, Lyman-$alpha$)
- NH molecular bands ($A^3 Pi -> X^3 Sigma^-$)
- Atomic lines ($H_alpha$, $H_beta$, N lines)

*Spatial resolution*: Spectra were recorded at different positions across the discharge gap to understand spatial variations in excited state populations.

*Temporal evolution*: Time-resolved measurements captured transient phenomena and discharge stability characteristics.

*Parameter studies*: Spectra were recorded across different operating conditions to understand the dependence of excited state populations on discharge parameters.

The spectroscopic data provided valuable insights into:
- Electron energy distribution function characteristics
- Excited state chemistry and energy transfer processes
- Discharge uniformity and stability
- Validation of theoretical models

=== Ammonia production rates
Ammonia production rates were measured and analyzed:

*Production efficiency*: $"NH"_3$ production per unit energy input
*Parameter optimization*: Conditions for maximum ammonia production
*Mechanism analysis*: Identification of key reaction pathways
*Comparison with literature*: Validation against published data

The analysis revealed:
- Optimal conditions for ammonia production
- Key reaction pathways for ammonia formation
- Energy efficiency considerations
- Scaling considerations for industrial applications

=== Model validation and refinement needs
The experimental results were used to validate and refine the kinetic model:

*Model performance assessment*: Quantitative comparison with experimental data
*Parameter sensitivity analysis*: Identification of key model parameters
*Mechanism refinement*: Addition or modification of reactions
*Uncertainty reduction*: Improved rate coefficient estimates

The validation process identified:
- Areas of good agreement between model and experiment
- Systematic discrepancies requiring model refinement
- Missing reaction pathways
- Improved rate coefficient estimates

The refinement process included:
- Addition of missing reactions
- Adjustment of rate coefficients
- Improved cross-section data
- Enhanced surface reaction models
